{
    "Function Activity Details": {
        "function_name": "ETL_PipeLine",
        "github_repo_folder_dir": "Logging-Activity/General-Log",
        "purpose": "",
        "kwargs": {
            "status_code": "N/A",
            "status": "ETL_PipeLine Execution Failed",
            "message": "",
            "error": "Traceback (most recent call last):\n  File \"/root/.ipykernel/958/command-2784750537705050-3956212021\", line 218, in ETL_Transformation\n    count(\"*\").alias(\"Person Voted\"),\n    ^^^^^\nNameError: name 'count' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ipykernel/958/command-2784750537705050-3956212021\", line 363, in <module>\n    tranformed_df = ETL_Transformation()\n                   ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.ipykernel/958/command-2784750537705050-3956212021\", line 290, in ETL_Transformation\n    write_log(function_name=\"Tranformation\", error=error_mesasge , status=\"Function Execution Failed\")\n                                                   ^^^^^^^^^^^^^\nNameError: name 'error_mesasge' is not defined\n",
            "log_type": "info"
        }
    },
    "last_log_time": "2024-09-10 13:50:18-767751"
}